application: v5gamesdotcom
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "300d 5h"

handlers:

- url: /static/*
  static_dir: static
  http_headers:
    Vary: Accept-Encoding
#
#- url: /favicon.ico
#  static_files: static/favicon.ico
#  upload: static/favicon.ico
#- url: /apple-touch-icon.png
#  static_files: static/apple-touch-icon.png
#  upload: static/apple-touch-icon.png
#- url: /BingSiteAuth.xml
#  static_files: static/BingSiteAuth.xml
#  upload: static/BingSiteAuth.xml
#- url: /channel.html
#  static_files: static/channel.html
#  upload: static/channel.html
#
- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt
  http_headers:
    Vary: Accept-Encoding
  expiration: "0d 1h"

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"

instance_class: F1
automatic_scaling:
  max_pending_latency: 7.5s
# automatic_scaling:
#   min_idle_instances: 2
#   max_pending_latency: 4.5s

pagespeed:

#  url_blacklist:
#  - http://www.evangeler.com/music/*
#  - http://www.evangeler.com/sitemap
#  - http://www.evangeler.com/manifest.webapp
#  - https://evangeler.appspot.com/buy
  enabled_rewriters:
  - CollapseWhitespace
  - CombineHeads
  # - ElideAttributes
  - RemoveComments
  - MinifyCss
  # - InlineJs
  # - LeftTrimUrls

inbound_services:
- warmup

# YOLO cost saving autoscaling
automatic_scaling:
  max_idle_instances: 1
  target_cpu_utilization: .95
  target_throughput_utilization: .95
  min_pending_latency: 300ms
  max_pending_latency: 15000ms
  max_concurrent_requests: 80

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules.*$
